language: go
sudo: false
go:
  - 1.5.2
  - 1.6beta1
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
addons:
  apt:
    packages:
      - rsyslog
before_script:
  - rsyslogd &
script:
  - make test
  - ./check-fmt.sh
services: mongodb
